Repository mim-uw/eXplainableMachineLearning-2023, pull requests merged in 2022-10, with the labels that each got.

#5 Add HW1 Krystian Sztenderski
  Homeworks/HW1/KrystianSztenderski/imgs/accuracy_score.png
  Homeworks/HW1/KrystianSztenderski/imgs/f1_score.png
  Homeworks/HW1/KrystianSztenderski/imgs/features_dist.png
  Homeworks/HW1/KrystianSztenderski/main.ipynb
Labels: results OK need comments

#6 Added HW1 - Michał Siennicki
  Homeworks/HW1/MichalSiennicki/heart_attack.ipynb
Labels: results OK need comments

#13 Add hw1 Kamil Grudzień
  Homeworks/HW1/KamilGrudzien/hw1.ipynb
Labels: results OK need comments

#18 homework 1 submitted (Mateusz Błajda)
  Homeworks/HW1/MateuszBłajda/MateuszBłajda.ipynb
Labels: results OK need comments

#24 Add homework 1 Krzysztof Tomala
  Homeworks/HW1/Homework-1-Krzysztof-Tomala.ipynb
  Homeworks/HW1/heart.csv
Labels: results OK need comments

#2 JakubSkrajny_homeworks
  Homeworks/HW1/JakubSkrajny/main.ipynb
  Homeworks/HW2/JakubSkrajny/main..ipynb
Labels: results OK need comments

#14 Maciej Nadolski, HW1
  Homeworks/HW1/MaciejNadolski/solution.ipynb
Labels: results OK need comments

#22 HW1 Szymon Tworkowski
  Homeworks/HW1/SzymonTworkowski/hw1_st.ipynb
Labels: results OK need comments

#3 Jakub Walendowski HW1 brain stroke
  .idea/eXplainableMachineLearning-2023.iml
  Homeworks/HW1/JakubWalendowski/brain_stroke.ipynb
Labels: results OK need comments

#31 adding homework 1 and 2
  Homeworks/HW1/MaciejDomaradzki/HW1_Maciej_Domaradzki.ipynb
  Homeworks/HW1/MaciejDomaradzki/heart.csv
  Homeworks/HW1/MaciejDomaradzki/img.png
  Homeworks/HW2/MaciejDomaradzki/HW2_Maciej_Domaradzki.ipynb
  Homeworks/HW2/MaciejDomaradzki/heart.csv
  Homeworks/HW2/MaciejDomaradzki/img.png
  Homeworks/HW2/MaciejDomaradzki/plot0.png
  Homeworks/HW2/MaciejDomaradzki/plot1.png
  Homeworks/HW2/MaciejDomaradzki/plot2.png
  Homeworks/HW2/MaciejDomaradzki/plot3.png
  Homeworks/HW2/MaciejDomaradzki/plot4.png
  Homeworks/HW2/MaciejDomaradzki/plot_dal.png
  Homeworks/HW2/MaciejDomaradzki/plot_lr.png
Labels: results OK need comments

#16 HW1+HW2 Paulina Kaczyńska
  Homeworks/HW1/PaulinaKaczynska/HW1_Paulina_Kaczynska (2).ipynb
  Homeworks/HW2/Paulina Kaczyńska/XAI_HW2(1).html
  Homeworks/HW2/Paulina Kaczyńska/XAI_HW2(1).ipynb
Labels: more than one HWs in a single PR

#44 HW1 Mateusz Cedro HB
  Homeworks/HW1/MateuszCedro/HM1_stroke.ipynb
Labels: external

#49 Edward Sucharda HW2
  Homeworks/HW2/EdwardSucharda/.txt
  Homeworks/HW2/EdwardSucharda/XAI_homework2_report.html
  Homeworks/HW2/EdwardSucharda/XAI_homework2_report.ipynb
  Homeworks/HW2/EdwardSucharda/heart.csv
Labels: results OK wrong format

#15 Added assignment 1
  Homeworks/HW1/MichalKrutul/XAI_1.ipynb
Labels: results OK need comments

#8 hw1 kajetan husiatynski
  Homeworks/HW1/KajetanHusiatynski/hw1.ipynb
Labels: results OK need comments

#54 Add HW2
  Homeworks/HW2/StanislawFrejlak/Homework2.html
  Homeworks/HW2/StanislawFrejlak/Homework2.ipynb
Labels: late/part missing

#60 Added HM2
  Homeworks/HW2/MichalKrutul/xai_2.html
  Homeworks/HW2/MichalKrutul/xai_2.ipynb
Labels: results OK need comments

#80 Add solution to HW 3
  Homeworks/HW3/MaciejPióro/images/1.png
  Homeworks/HW3/MaciejPióro/images/14.png
  Homeworks/HW3/MaciejPióro/images/2.png
  Homeworks/HW3/MaciejPióro/images/3.png
  Homeworks/HW3/MaciejPióro/images/4.png
  Homeworks/HW3/MaciejPióro/images/6.png
  Homeworks/HW3/MaciejPióro/images/7.png
  Homeworks/HW3/MaciejPióro/images/8.png
  Homeworks/HW3/MaciejPióro/images/9.png
  Homeworks/HW3/MaciejPióro/images/shap.png
  Homeworks/HW3/MaciejPióro/solution.html
  Homeworks/HW3/MaciejPióro/solution.ipynb
Labels: results OK need comments
