Repository mim-uw/eXplainableMachineLearning-2023, pull requests merged in 2022-11, with the labels that each got.

#72 Add hw3
  Homeworks/HW3/KamilGrudzien/hw3.html
  Homeworks/HW3/KamilGrudzien/hw3.ipynb
  Homeworks/HW3/KamilGrudzien/imgs/3_pat_0_seed_0.png
  Homeworks/HW3/KamilGrudzien/imgs/3_pat_0_seed_12.png
  Homeworks/HW3/KamilGrudzien/imgs/3_pat_0_seed_42.png
  Homeworks/HW3/KamilGrudzien/imgs/3_pat_1_seed_0.png
  Homeworks/HW3/KamilGrudzien/imgs/3_pat_1_seed_12.png
  Homeworks/HW3/KamilGrudzien/imgs/3_pat_1_seed_42.png
  Homeworks/HW3/KamilGrudzien/imgs/4_pat_0.png
  Homeworks/HW3/KamilGrudzien/imgs/4_pat_1.png
  Homeworks/HW3/KamilGrudzien/imgs/5_pat_0.png
  Homeworks/HW3/KamilGrudzien/imgs/5_pat_1.png
Labels: wrong directory

#81 HW3
  Homeworks/HW3/MichalKrutul/xai_3.html
  Homeworks/HW3/MichalKrutul/xai_3.ipynb
Labels: results OK need comments

#27 Mtyrolski hw1
  Homeworks/HW1/MichalTyrolski/.keep
  Homeworks/HW1/MichalTyrolski/mt406390_xai1.ipynb
Labels: results OK need comments

#51 [HW2] [HB] Kajetan Husiatynski
  Homeworks/HW2/KajetanHusiatynski/4_alternative.png
  Homeworks/HW2/KajetanHusiatynski/7_linear.png
  Homeworks/HW2/KajetanHusiatynski/bad_shap.png
  Homeworks/HW2/KajetanHusiatynski/dalex.png
  Homeworks/HW2/KajetanHusiatynski/good_shap.png
  Homeworks/HW2/KajetanHusiatynski/hw2.html
  Homeworks/HW2/KajetanHusiatynski/hw2.ipynb
Labels: technical error

#28 Szymon Antoniak hw1 + hw2 + hw3
  Homeworks/HW1/SzymonAntoniak/heart.csv
  Homeworks/HW1/SzymonAntoniak/szymona-hw1-xai.ipynb
  Homeworks/HW2/SzymonAntoniak/appendix.ipynb
  Homeworks/HW2/SzymonAntoniak/report.html
  Homeworks/HW2/SzymonAntoniak/shap.txt
  Homeworks/HW3/SzymonAntoniak/appendix.ipynb
  Homeworks/HW3/SzymonAntoniak/report.html
Labels: more than one HWs in a single PR, results OK wrong format
